package cn.huan.community.community.domain;

public class Tag {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag.id
     *
     * @mbg.generated Tue Aug 04 15:22:55 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag.tag_name
     *
     * @mbg.generated Tue Aug 04 15:22:55 CST 2020
     */
    private String tagName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag.parent_id
     *
     * @mbg.generated Tue Aug 04 15:22:55 CST 2020
     */
    private Integer parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag.parent_tag_name
     *
     * @mbg.generated Tue Aug 04 15:22:55 CST 2020
     */
    private String parentTagName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag.id
     *
     * @return the value of tag.id
     *
     * @mbg.generated Tue Aug 04 15:22:55 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag.id
     *
     * @param id the value for tag.id
     *
     * @mbg.generated Tue Aug 04 15:22:55 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag.tag_name
     *
     * @return the value of tag.tag_name
     *
     * @mbg.generated Tue Aug 04 15:22:55 CST 2020
     */
    public String getTagName() {
        return tagName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag.tag_name
     *
     * @param tagName the value for tag.tag_name
     *
     * @mbg.generated Tue Aug 04 15:22:55 CST 2020
     */
    public void setTagName(String tagName) {
        this.tagName = tagName == null ? null : tagName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag.parent_id
     *
     * @return the value of tag.parent_id
     *
     * @mbg.generated Tue Aug 04 15:22:55 CST 2020
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag.parent_id
     *
     * @param parentId the value for tag.parent_id
     *
     * @mbg.generated Tue Aug 04 15:22:55 CST 2020
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag.parent_tag_name
     *
     * @return the value of tag.parent_tag_name
     *
     * @mbg.generated Tue Aug 04 15:22:55 CST 2020
     */
    public String getParentTagName() {
        return parentTagName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag.parent_tag_name
     *
     * @param parentTagName the value for tag.parent_tag_name
     *
     * @mbg.generated Tue Aug 04 15:22:55 CST 2020
     */
    public void setParentTagName(String parentTagName) {
        this.parentTagName = parentTagName == null ? null : parentTagName.trim();
    }
}